# Generated by Django 4.2 on 2023-04-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_topic_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
